[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.15"
remappings = [
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/",
    "safe-contracts/=lib/safe-contracts/contracts/",
    "@gnosis.pm/=lib/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config